### ISSUE TITLE
Ran into errors when building the solution

### ISSUE THREAD

**Issue by dotnetcontributer** [amantinband/clean-architecture#1]
Hey Amichai,

Thanks a bunch for the cool project. I gave it a shot for the first time using these commands:

dotnet new install Amantinband.CleanArchitecture.Template
dotnet new clean-arch -o CleanArchitectureByAB

But I ran into errors when building the solution. Any suggestions on how to fix it?

![image](https://github.com/amantinband/clean-architecture/assets/90146568/60f5de11-89f1-46b2-8250-20a85cc6c788)

Thanks once more!

**Comment by amantinband** [comment]
Interesting.. can you run ‘dotnet build’ via the dotnet CLI and paste here the output? Also, have you tried cloning the GitHub project and building? If yes, do you run into the same issue?

**Comment by dotnetcontributer** [comment]
> Interesting.. can you run ‘dotnet build’ via the dotnet CLI and paste here the output? Also, have you tried cloning the GitHub project and building? If yes, do you run into the same issue?

Ye, I've cloned the main project and it can be built.

Here's the result after building the nugget package:

[Build Log.txt](https://github.com/amantinband/clean-architecture/files/13691692/Build.Log.txt)

**Comment by amantinband** [comment]
I misconfigured the publish action.

Should be fixed now 🤞

Try installing the latest version of the template and let me know if we can close this issue:

```
dotnet new install Amantinband.CleanArchitecture.Template::1.0.1
```

**Comment by dotnetcontributer** [comment]
Thanks, Amichai. Works fine now. 🤞
