### ISSUE TITLE
The FluentValidation.AspNetCore package is no longer being maintained

### ISSUE THREAD

**Issue by viktorsarkany** [amantinband/clean-architecture#17]

**Comment by xavierjohn** [comment]
Where does it say that?
https://docs.fluentvalidation.net/en/latest/

**Comment by ccaesarw** [comment]
In the README.md
https://github.com/FluentValidation/FluentValidation.AspNetCore/commit/347b0535e5fe93bdc39ca031b3f971e0af1619b4

They recommend moving away from this package and use the core FluentValidation package with a manual validation approach as detailed at  https://docs.fluentvalidation.net/en/latest/aspnet.html

**Comment by xavierjohn** [comment]
I replaced FluentValidation.AspNetCore with FunctionalDdd.FluentValidation
https://github.com/xavierjohn/clean-architecture/commit/02234fb93c5b0f29ec18f38911a71e6788f17192

Invalid commands can no longer be created. The constructor is private and does not rely on mediator Validation Behaviour.
