### ISSUE TITLE
Errors about Order Usings

### ISSUE THREAD

**Issue by XuanPH** [amantinband/clean-architecture#2]
Hello Amichai,

Thanks for amazing project, that template I always looking for. 

I have an issue about "Order usings directive." 

![image](https://github.com/amantinband/clean-architecture/assets/26076388/180d27b8-891c-49c8-9f1f-5d69f4f117a2)

The error is: `Using directives should be ordered alphabetically by the namespaces (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1210.md)`

I'm using Rider, do you have any idea to fix this, Currently I'm fixing it manually.

**Comment by amantinband** [comment]
Are you getting these errors on a clean template created using `dotnet new clean-arch..`? If yes, are you getting the same error when building via `dotnet build` in the CLI? If yes, make sure you didn't delete your `.editorconfig` file in the root directory.

In any case, you can suppress the error in your `.editorconfig` by adding the following suppression:

```csharp
# SA1210: Using directives should be ordered alphabetically by the namespaces 
dotnet_diagnostic. SA1210.severity = none
```

**Comment by XuanPH** [comment]
> Are you getting these errors on a clean template created using `dotnet new clean-arch..`? If yes, are you getting the same error when building via `dotnet build` in the CLI? If yes, make sure you didn't delete your `.editorconfig` file in the root directory.
> 
> In any case, you can suppress the error in your `.editorconfig` by adding the following suppression:
> 
> ```cs
> # SA1210: Using directives should be ordered alphabetically by the namespaces 
> dotnet_diagnostic. SA1210.severity = none
> ```

Thanks a lot, it's works for me.
