### ISSUE TITLE
Conflicts with ardalis clean architecture template

### ISSUE THREAD

**Issue by Aminga-Nyaoso** [amantinband/clean-architecture#23]
After installing the template, I can not create a project using the template because it uses the same identifier (clean-arch) as another template from Ardalis. Consider giving it a differenet ID

**Comment by amantinband** [comment]
Right, didn't notice the name conflict.

You can create the template via the package id:
```
dotnet new Amantinband.CleanArchitecture -o CleanArchitecture
```
