### ISSUE TITLE
Links to Figma designs?

### ISSUE THREAD

**Issue by Thijs153** [amantinband/clean-architecture#26]
Hey Amichai, I've been watching your videos for a while now, and I'm sure I'll use this template for future projects 🙌
Quick question. Could you share the link to the Figma designs you've used for this template (The folder structure/ test overviews, etc)?

I'd like to create similar designs/ update them for my projects.

**Comment by amantinband** [comment]
Hey, I published a community file with the file system following your suggestion: https://www.figma.com/community/file/1334042945934670571/clean-architecture-project-file-system

I also updated the readme: https://github.com/amantinband/clean-architecture?tab=readme-ov-file#folder-structure-

Thanks for the suggestion 🙏
