### ISSUE TITLE
Question: Converters

### ISSUE THREAD

**Issue by Thijs153** [amantinband/clean-architecture#29]
Hey Amichai, I have a quick question. In this template, you're storing a list of IDs as a comma-separated string in the db (.HasListOfIdsConverter();), and you're also storing a dictionary as JSON in the database. 

I'm wondering if it's a recommended/good approach, or just for this template? Wouldn't you normally store these in a separate table (like you did in your YT series)?

(I'm using SQL server, if it's db specific :) )

**Comment by pointlevel** [comment]
Did you get an answer on this question?

**Comment by Thijs153** [comment]
Not directly, but I've come to realize that this is a more general .NET/SQL question, rather than it being an 'issue' for this template.
