### ISSUE TITLE
Change "AddInfrastructureMiddleware" to "UseInfrastructureMiddleware"

### ISSUE THREAD

**Issue by amirhessampourhossein** [amantinband/clean-architecture#3]
Hello @amantinband
First of all, I want to thank you for your great clean architecture template. Recently, I have been learning about Clean Architecture and DDD and your YouTube channel taught me a lot about these topics. Thanks a million. 🙏

I have noticed that you use the 'AddInfrastructureMiddleware' extension method to register your EventualConsistencyMiddleware
I think it would be a good idea to change the name to UseInfrastructureMiddleware.

**Comment by amantinband** [comment]
Yeah Use is a better choice here. Not sure why I went with Add in the first place.

**Comment by amantinband** [comment]
Changed to `UseInfrastructure`. Thanks for the feedback amir
