### ISSUE TITLE
Adding constants for custom claims

### ISSUE THREAD

**Issue by amirhessampourhossein** [amantinband/clean-architecture#5]
In your `JwtTokenGenerator` class there are two magic strings used as custom claim names.
we could use constants like below 👇

```c#
public static class CustomClaims
{
    public const string Id = "id";
    public const string Permissions = "permissions";
}
```
what do you think ? @amantinband

**Comment by amantinband** [comment]
Nah, when constant strings are used only in one place and there isn't added value by extracting them to a separate location I prefer inlining them.
