### ISSUE TITLE
Purpose of just calling Property()

### ISSUE THREAD

**Issue by amirhessampourhossein** [amantinband/clean-architecture#6]
I have seen the code below in your fluent configuration for `User`
```c#
builder.Property(u => u.Email);

builder.Property(u => u.LastName);

builder.Property(u => u.FirstName);
```
Is there a reason for calling only the `.Property()` method with nothing else ?

**Comment by amantinband** [comment]
The properties aren't included by default since they don't have a getter and a setter, only a getter:
![image](https://github.com/amantinband/clean-architecture/assets/39407673/eb6e38ce-d985-4d97-97fa-ec205f38aff7)

**Comment by amirhessampourhossein** [comment]
Thank you very much for taking the time. I was not aware of this ❤ @amantinband
