### ISSUE TITLE
Improving performance in "ApiController"

### ISSUE THREAD

**Issue by amirhessampourhossein** [amantinband/clean-architecture#8]
I am getting the [CA1859](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1859) suggestion in visual studio when hovering over `Problem(Error error)` and `ValidationProblem(List<Error> errors)` in `ApiController`
is it really a good idea to change the return type from `IActionResult` to `ActionResult` or `ObjectRresult` ?

**Comment by amantinband** [comment]
Yeah sure, let's change it since the type is known. Changed in a separate commit under #10
