### ISSUE TITLE
A slight change in Bind Configuration

### ISSUE THREAD

**Issue by ducware** [amantinband/clean-architecture#9]
What do you think if you change:
**Your code:**

```
configuration.Bind(EmailSettings.Section, emailSettings);
```

**The code becomes like this:**

```
configuration.Bind(nameof(EmailSettings), emailSettings);
```

Similar to other settings, this will probably be more flexible for code, I think, have a nice day!

**Comment by amantinband** [comment]
Hey Dang!

I prefer not to couple the `SectionName` class with the configuration section. I usually go with either what we currently have:
<img width="1125" alt="image" src="https://github.com/amantinband/clean-architecture/assets/39407673/06c8c9fa-6476-4fe3-856b-ff825ecc6513">

Or inlining the section name like so:
```cs
configuration.Bind("EmailSection", emailSettings);
```

Your approach is also very common, it's mostly a matter of taste
